### ISSUE TITLE
Error 500 on creating datasource

### ISSUE THREAD

**Issue by omaffeis** [sraoss/grafana-sqldb-datasource#1]
Hello,

I am really looking for a sqldb datasource as we already use a backend based on postgreSQL.
I tried this datasource.

The installation was straightforward but when I try to create a datasource, I got an error: Unknown error
SqlDB Error Response: Internal Server Error
In the logs of grafana, I have :

<YYYY/MM/DD> <HH:MM:SS> [I] Completed <ipaddr> admin "POST /query HTTP/1.1" 500 Internal Server Error 0 bytes in <int>us

I looked at the sent request and compared it to influxdb one. The value of "access" is "proxy". 
When I set it to "direct", I get an HTTP 200.
Could you provide this option in the datasource as the of influxdb does ? 

Regard,
Olivier

**Comment by anzai** [comment]
@omaffeis Sorry for not explaining well enough. This plugin cannot work without the patch for Grafana core now, and it seems you don't use this patch.
https://github.com/grafana/grafana/pull/5364

You can get the binary including the backend patch and this frontend plugin. Could you try this one?
https://github.com/sraoss/grafana-sqldb-datasource/releases/download/V0.1/grafana-sqldb_20160615.tar.gz

Sqldb provides only "proxy" mode because of the RDB's feature. We cannot connect to RDBs via HTTP GET directly, and have to make the backend perform the proxy.

**Comment by omaffeis** [comment]
My test was done with v3.0.4.

I will try it with your release as soon as possible.

Thank you again to provide this datasource.



________________________________
De : Nozomi Anzai <notifications@github.com>
Envoyé : lundi 27 juin 2016 01:52:40
À : sraoss/grafana-sqldb-datasource
Cc : omaffeis; Mention
Objet : Re: [sraoss/grafana-sqldb-datasource] Error 500 on creating datasource (#1)


@omaffeis<https://github.com/omaffeis> Sorry for not explaining well enough. This plugin cannot work without the patch for Grafana core now, and it seems you don't use this patch.
grafana/grafana#5364<https://github.com/grafana/grafana/pull/5364>

You can get the binary including the backend patch and this frontend plugin. Could you try this one?
https://github.com/sraoss/grafana-sqldb-datasource/releases/download/V0.1/grafana-sqldb_20160615.tar.gz

Sqldb provides only "proxy" mode because of the RDB's feature. We cannot connect to RDBs via HTTP GET directly, and have to make the backend perform the proxy.

-
